#!/usr/bin/env bash
# -*- coding: UTF-8 -*-
###############################################################################
# cmus
# ====
#
# Description:           Outputs the title of the currently playing song and a
#                        status icon.
# Authors:               Anachron
#                        Michael De Pasquale
# License:               GPL-3.0
#
# Source
# ------
# https://github.com/Anachron/i3blocks/blob/master/blocks/cmus
#
###############################################################################

# Get info and parse
INFO_CMUS=$(cmus-remote -Q 2>/dev/null)
INFO_STATUS=$(echo "$INFO_CMUS" | sed -n -e 's/^.*status\s*//p' | head -n 1)
INFO_TITLE=$(echo "$INFO_CMUS" | sed -n -e 's/^.*title\s*//p' | head -n 1)
INFO_FILE=$(echo "$INFO_CMUS" | sed -n -e 's/^.*file.*\///p' | head -n 1)

# Output icon (ICON)
if echo $INFO_STATUS | grep -P '[Pp]laying' > /dev/null; then
    ICON=''
elif echo $INFO_STATUS | grep -P '[Pp]aused'> /dev/null; then
    ICON=''
elif echo $INFO_STATUS | grep -P '[Ss]topped'> /dev/null; then
    ICON=''
fi

# Title only
if [ -z "$INFO_TITLE" ]; then
    INFO_TITLE="$INFO_FILE"
fi

# Long
printf " %s %s\n" "$ICON" "$INFO_TITLE"

# Short
printf " %s %s\n" "$ICON" "$INFO_TITLE"

# Colour (omitted)
print '\n'

exit 0

# vim: set ts=4 sw=4 tw=79 fdm=manual et :
