#!/usr/bin/env bash
# -*- coding: UTF-8 -*-
###############################################################################
# config
# ======
# Description:           i3-gaps configuration file
# Author:                Michael De Pasquale <shaggyrogers>
# Creation Date:         2017-11-01
# Modification Date:     2018-03-03
# License:               MIT
###############################################################################

# Options{{{
# Key configuration{{{
# Super_L / Alt_L / Shift / Control_L
set $down   j
set $down2  Down
set $left   h
set $left2  Left
set $mod1 Mod4
set $mod2 Mod1
set $mod3 Shift
set $mod4 'control'
set $right  l
set $right2 Right
set $up     k
set $up2    Up
# }}}
# Applications{{{
# Per-application window settings{{{
for_window [class="conky_time"]             floating enable
for_window [class="conky_time"]             sticky enable
for_window [class="conky_task"]             floating enable
for_window [class="conky_task"]             sticky enable
for_window [class="KeePass2"]          floating enable
for_window [class="KeePass2"]          sticky enable
for_window [class="KeePass2"]          resize set 1024 640
for_window [class="KeePass2"]          move absolute position 16 16
for_window [class="KeePass2"]          move to scratchpad
for_window [class="GParted"]           floating enable
for_window [class="GParted"]           resize set 1024 640
for_window [class="GParted"]           move absolute position 1048 16
for_window [class="Seahorse"]          floating enable
for_window [class="Seahorse"]          resize set 1024 640
for_window [class="Seahorse"]          move absolute position 16 664
for_window [class="kittydropdownterm"] floating enable
for_window [class="kittydropdownterm"] resize set 2544 480
for_window [class="kittydropdownterm"] move position 8 -6
# }}}
# Media player commands{{{
# Clementine{{{
set $clementinePlay  "qdbus org.mpris.MediaPlayer2.clementine /org/mpris/MediaPlayer2 PlayPause"
set $clementinePause "qdbus org.mpris.MediaPlayer2.clementine /org/mpris/MediaPlayer2 PlayPause"
set $clementineNext  "qdbus org.mpris.MediaPlayer2.clementine /org/mpris/MediaPlayer2 Next"
set $clementinePrev  "qdbus org.mpris.MediaPlayer2.clementine /org/mpris/MediaPlayer2 Previous"
# }}}
# cmus{{{
set $cmusPlay            "$HOME/.config/cmus/cmus-playpause-launch.sh"
set $cmusPause           "$HOME/.config/cmus/cmus-playpause-launch.sh"
set $cmusNext            "cmus-remote --next"
set $cmusPrev            "cmus-remote --prev"
# }}}
# }}}
# }}}
# Workspaces{{{
set $ws01 "1:work"
set $ws02 "2:proj1"
set $ws03 "3:proj2"
set $ws04 "4:misc1"
set $ws05 "5:misc2"
set $ws06 "6:social"
set $ws07 "7:todo"
set $ws08 "8:media"
set $ws09 "9:sysmon"
set $ws10 "10:sysconf"
set $ws11 "11:srvmon"
set $ws12 "12:misc3"
set $ws13 "13:misc4"
set $ws14 "14:misc5"
set $ws15 "15:misc6"
set $ws16 "16:misc7"
set $ws17 "17:misc8"
set $ws18 "18:btc"
set $ws19 "19:tor"
set $ws20 "20:tails"
assign [class="google-chrome"]   $ws06
assign [title="Taskwarrior"]     $ws07
assign [class="cmusmusicplayer"] $ws08
# }}}
# Appearance{{{
# General{{{
default_orientation auto
font pango:Arimo Nerd Font Bold 12
hide_edge_borders both
new_window pixel 6
workspace_layout default
# }}}
# Status bar{{{
set $bar_background #00000000
set $bar_separator #00000000
set $bar_statusline #4B5262
set $bar_font pango:Arimo Nerd Font, Weather Icons
set $bar_separator_symbol " "
# }}}
# Workspace indicator{{{
set $focused_workspace_bg       #84AACD
set $focused_workspace_border   #84AACD
set $focused_workspace_text     #454C5B
set $inactive_workspace_bg      #00405C
set $inactive_workspace_border  #00405C
set $inactive_workspace_text    l454C5B
set $unfocused_workspace_bg     #00405C
set $unfocused_workspace_border #00405C
set $urgent_workspace_bg        #00585C
set $urgent_workspace_border    #005F88
set $urgent_workspace_text      #005F88
# }}}
# Windows{{{
set $focused_window_bg #E1E8F0
set $focused_window_border #E1E8F0
set $focused_window_text #005F88
set $inactive_window_bg #5F88B1
set $inactive_window_border #005F88
set $inactive_window_text #E1E8F0
set $unfocused_window_bg #005F88
set $unfocused_window_border #005F88
set $unfocused_window_text #AFCCDD
set $urgent_window_bg #eb709b
set $urgent_window_border #5B97CF
set $urgent_window_text #FAFBFC
# }}}
# Configure windows{{{
client.focused $focused_window_border $focused_window_bg $focused_window_text
client.focused_inactive $inactive_window_border $inactive_window_bg $inactive_window_text
client.unfocused $unfocused_window_border $unfocused_window_bg $unfocused_window_text
client.urgent $urgent_window_border $urgent_window_bg $urgent_window_text
# }}}
# Configure Status bar{{{
bar {
    font $bar_font
    i3bar_command i3bar -t
    mode hide
    position bottom
    separator_symbol $bar_separator_symbol
    status_command i3blocks -c ~/.config/i3/i3blocks.conf
    strip_workspace_numbers yes

    colors {
        background $bar_background
        separator $bar_separator
        statusline $bar_statusline
        active_workspace $focused_workspace_border $focused_workspace_bg $focused_workspace_text
        focused_workspace $focused_workspace_border $focused_workspace_bg $focused_workspace_text
        inactive_workspace $inactive_workspace_border $inactive_workspace_bg $inactive_workspace_text
        urgent_workspace $urgent_workspace_border $urgent_workspace_bg $urgent_workspace_text
    }
}
# }}}
# }}}
# Misc{{{
workspace_auto_back_and_forth yes
focus_follows_mouse           no
floating_modifier             $mod1
gaps                          inner 12
gaps                          outer 4
# }}}
# }}}

# Shortcuts{{{
# Application shortcuts{{{
#bindsym --release $mod1+$mod2+Return exec kitty
bindsym --release $mod1+$mod2+Return exec ~/.local/bin/kitty
bindsym --release $mod1+$mod2+$mod3+Return exec gnome-terminal
bindsym --release $mod1+$mod3+Return exec ~/.local/bin/kitty \
--class=kittydropdownterm
bindsym --release $mod1+$mod2+b      exec ~/.local/bin/kitty --class=ranger \
'ranger'
bindsym --release $mod1+$mod3+b      exec nemo
bindsym --release $mod1+$mod2+c      exec rofi -modi calc:wcalc -show \
calc:wcalc
bindsym --release $mod1+$mod3+c      exec gnome-calculator
bindsym --release $mod1+$mod2+e      exec kitty-nvim -i 0
bindsym --release $mod1+$mod3+e      exec kitty-nvim -i 1
bindsym --release $mod1+$mod2+i      exec firefox
bindsym --release $mod1+$mod3+i      exec google-chrome
bindsym --release $mod1+$mod2+p      [class=KeePass2] scratchpad show
bindsym --release $mod1+$mod3+p      exec ~/.local/bin/kitty --class=aptitude \
--override background_opacity=1.0 'aptitude'
bindsym --release $mod1+$mod2+q      exec xkill
bindsym --release $mod1+$mod2+w      exec ~/.local/bin/i3-switch-workspace
bindsym --release $mod1+Escape       exec beep
bindsym --release $mod1+d            exec rofi -show run -modi run
bindsym --release $mod1+q            kill
bindsym --release $mod1+Print        exec gnome-screenshot
bindsym --release $mod1+$mod2+Print  exec sh -c "gnome-screenshot -a"
bindsym --release $mod1+$mod3+Print  exec sh -c "gnome-screenshot -a"

# }}}
# Insert text {{{
bindsym --release $mod1+$mod2+$mod3+c      exec input-type c
bindsym --release $mod1+$mod2+$mod3+f      exec input-type f
bindsym --release $mod1+$mod2+$mod3+p      exec input-type p
bindsym --release $mod1+$mod2+$mod3+s      exec input-type s
# }}}
# Container layout{{{
# Mod1 + s / w / e : Change layout to stacked/tabbed/split){{{
bindsym $mod1+s layout stacking
bindsym $mod1+w layout tabbed
bindsym $mod1+e layout toggle split
# }}}
# Mod1 + v / Mod1 + Mod2 + h : Split container vertically/horizontally{{{
bindsym $mod1+v split v
bindsym $mod1+$mod2+v split h
# }}}
# Mod1 + f : Toggle fullscreen for focused container{{{
bindsym $mod1+f fullscreen toggle
# }}}
# Mod1 + Mod2 + Space : Toggle floating for focused container{{{
bindsym $mod1+$mod2+space floating toggle
# }}}
# Mod1 + Space : Switch between floating and tiling window focus{{{
bindsym $mod1+space focus mode_toggle
# }}}
# }}}
# Misc{{{
# Mod1 + R : Reload configuration file/restart i3 in-place{{{
bindsym $mod1+r reload
bindsym $mod1+$mod2+r restart
# }}}
#bindsym $mod1+$mod2+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"
# Volume controls{{{
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
# }}}
# Media keys : Play / Pause / Next / Previous{{{
bindsym--release XF86AudioPlay exec --no-startup-id $cmusPlay
bindsym --release XF86AudioPause exec --no-startup-id $cmusPause
bindsym --release XF86AudioNext exec --no-startup-id $cmusNext
bindsym --release XF86AudioPrev exec --no-startup-id $cmusPrev
# }}}
# }}}
# Window/container shortcuts{{{
# Change focus using vim movement keys{{{
bindsym $mod1+$left focus left
bindsym $mod1+$down focus down
bindsym $mod1+$up focus up
bindsym $mod1+$right focus right
# }}}
# ...using cursor keys{{{
bindsym $mod1+$left2 focus left
bindsym $mod1+$down2 focus down
bindsym $mod1+$up2 focus up
bindsym $mod1+$right2 focus right
# }}}
# focus the parent/child containers{{{
bindsym $mod1+a focus parent
bindsym $mod1+$mod2+a focus child
# }}}
# Move focused window using vim movement keys{{{
bindsym $mod1+$mod2+$left move left
bindsym $mod1+$mod2+$down move down
bindsym $mod1+$mod2+$up move up
bindsym $mod1+$mod2+$right move right
# }}}
# Move focused window using cursor keys{{{
bindsym $mod1+$mod2+$left2 move left
bindsym $mod1+$mod2+$down2 move down
bindsym $mod1+$mod2+$up2 move up
bindsym $mod1+$mod2+$right2 move right
# }}}
# Resize container using vim movement keys{{{
bindsym $mod1+$mod3+$left resize shrink width 10 px or 10 ppt
bindsym $mod1+$mod3+$down resize grow height 10 px or 10 ppt
bindsym $mod1+$mod3+$up resize shrink height 10 px or 10 ppt
bindsym $mod1+$mod3+$right resize grow width 10 px or 10 ppt
# }}}
# Resizing container using cursor movement keys{{{
bindsym $mod1+$mod3+$left2 resize shrink width 10 px or 10 ppt
bindsym $mod1+$mod3+$up2 resize grow height 10 px or 10 ppt
bindsym $mod1+$mod3+$down2 resize shrink height 10 px or 10 ppt
bindsym $mod1+$mod3+$right2 resize grow width 10 px or 10 ppt
# }}}
# }}}
# Workspaces{{{
# Mod1 + Tab / Mod3 + Tab / Mod2 + Mod3 + Left/Right : next/prev workspace {{{
bindsym $mod1+$mod2+$mod3+$left  workspace prev
bindsym $mod1+$mod2+$mod3+$right workspace next
bindsym $mod1+$mod3+Tab         workspace prev
bindsym $mod1+Tab               workspace next
# }}}
# Mod1 + Mod2 + Mod3 + Up/Down : Move window to next/previous workspace{{{
bindsym $mod1+$mod2+$mod3+$down exec "i3-msg move workspace prev; \
i3-msg workspace prev"
bindsym $mod1+$mod2+$mod3+$up   exec "i3-msg move workspace next; \
i3-msg workspace next"
# }}}
# Mod1 + 0-9, Mod1 + Mod3 + 0-9 : Jump to workspace{{{
bindsym $mod1+1 workspace $ws01
bindsym $mod1+2 workspace $ws02
bindsym $mod1+3 workspace $ws03
bindsym $mod1+4 workspace $ws04
bindsym $mod1+5 workspace $ws05
bindsym $mod1+6 workspace $ws06
bindsym $mod1+7 workspace $ws07
bindsym $mod1+8 workspace $ws08
bindsym $mod1+9 workspace $ws09
bindsym $mod1+0 workspace $ws10
bindsym $mod1+$mod3+1 workspace $ws11
bindsym $mod1+$mod3+2 workspace $ws12
bindsym $mod1+$mod3+3 workspace $ws13
bindsym $mod1+$mod3+4 workspace $ws14
bindsym $mod1+$mod3+5 workspace $ws15
bindsym $mod1+$mod3+6 workspace $ws16
bindsym $mod1+$mod3+7 workspace $ws17
bindsym $mod1+$mod3+8 workspace $ws18
bindsym $mod1+$mod3+9 workspace $ws19
bindsym $mod1+$mod3+0 workspace $ws20
# }}}
# Mod1 + Mod2 + 0-9, Mod1 + Mod2 + Mod3 + 0-9 : Move container to workspace{{{
bindsym $mod1+$mod2+1 move container to workspace $ws01
bindsym $mod1+$mod2+2 move container to workspace $ws02
bindsym $mod1+$mod2+3 move container to workspace $ws03
bindsym $mod1+$mod2+4 move container to workspace $ws04
bindsym $mod1+$mod2+5 move container to workspace $ws05
bindsym $mod1+$mod2+6 move container to workspace $ws06
bindsym $mod1+$mod2+7 move container to workspace $ws07
bindsym $mod1+$mod2+8 move container to workspace $ws08
bindsym $mod1+$mod2+9 move container to workspace $ws09
bindsym $mod1+$mod2+0 move container to workspace $ws10
bindsym $mod1+$mod2+$mod3+1 move container to workspace $ws11
bindsym $mod1+$mod2+$mod3+2 move container to workspace $ws12
bindsym $mod1+$mod2+$mod3+3 move container to workspace $ws13
bindsym $mod1+$mod2+$mod3+4 move container to workspace $ws14
bindsym $mod1+$mod2+$mod3+5 move container to workspace $ws15
bindsym $mod1+$mod2+$mod3+6 move container to workspace $ws16
bindsym $mod1+$mod2+$mod3+7 move container to workspace $ws17
bindsym $mod1+$mod2+$mod3+8 move container to workspace $ws18
bindsym $mod1+$mod2+$mod3+9 move container to workspace $ws19
bindsym $mod1+$mod2+$mod3+0 move container to workspace $ws20
# }}}
# }}}
# }}}

# Launch startup applications{{{
exec --no-startup-id "compton -CGb --config '/home/michael/.config/compton.conf'"
exec --no-startup-id "feh ~/.config/i3/wallpaper.jpg --no-fehbg --bg-center"
exec --no-startup-id keepass2
exec --no-startup-id "google-chrome 'http://messenger.com/' &"
exec --no-startup-id "kitty --class=cmusmusicplayer --override \
background_opacity=0.7 --override background='#202020' 'cmus' &"
exec --no-startup-id "conky -c /usr/share/conky/conky-time.conf &"
exec --no-startup-id "conky -c /usr/share/conky/active-task-timer.conf &"
exec --no-startup-id sh -c "tickr"

#exec --no-startup-id bash -c "(cd $HOME/'.local/taskwarriorc2'; . run.sh; exit 0) &"

# Start unified remote server
exec --no-startup-id "/opt/urserver/urserver-start --no-manager &"

# Start phabricator daemons
exec --no-startup-id sh -c "/var/www/html/phabricator_git_2018_03_18/phabricator/bin/phd start"

# Hide bar - Starts visible, until show key is pressed
exec --no-startup-id i3-msg bar hidden_state hide

# Lock screen
exec --no-startup-id sh -c "$HOME/.local/bin/lock &"
# }}}

#  vim: set ts=4 sw=4 tw=79 fdm=marker et :
