-- -*- coding: UTF-8 -*-
------------------------------------------------------------------------------
-- %FILEHEADING%
-- %FILEHEADINGULINE%
--
-- Version:               1.0.0
-- Author:                %USER%
-- Creation Date:         %DATE%
-- License:               %LICENSE%
--
-- Description
-- -----------
-- A short summary of this script and its purpose.
--
-- Usage
-- -----
-- How to use this script. Can leave this out if there are no arguments.
--
------------------------------------------------------------------------------

%HERE%
